services:
  - type: web
    name: intakeq-mcp-server
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python web_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
    scaling:
      minInstances: 1
      maxInstances: 3
    healthCheckPath: /health
